`26.0.1`, `25.0.6` and `24.0.12`
nextcloud/updater_server pull request #856
Opened 2023-04-19 15:53 UTC by skjnldsv

2023-04-19 16:54 UTC, nickvergessen requested changes

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-25.0.6.zip',
```suggestion
				'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-25.0.6.zip',
```

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-26.0.1.zip',
```suggestion
				'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-26.0.1.zip',
```

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-25.0.6.zip',
```suggestion
				'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-25.0.6.zip',
```

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-24.0.12.zip',
```suggestion
				'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-24.0.12.zip',
```

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-24.0.12.zip',
```suggestion
				'downloadUrl' => 'https://download.nextcloud.com/server/releases/nextcloud-24.0.12.zip',
```

2023-04-19 16:54 UTC, nickvergessen commented on config/config.php
> +				'downloadUrl' => 'https://download.nextcloud.com/server/prereleases/nextcloud-26.0.1.zip',
Same here and further

2023-04-20 06:33 UTC, skjnldsv commented on config/config.php
>  			'70' => [
Thanks for the heads up! :+1:

2023-04-20 07:24 UTC, nickvergessen approved these changes

2023-04-20 07:36 UTC, merged